# Generated by Django 5.2.10 on 2026-01-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='コース名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'コース',
                'verbose_name_plural': 'コース',
                'db_table': 'courses',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メンター名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'メンター',
                'verbose_name_plural': 'メンター',
                'db_table': 'mentors',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'db_table': 'tags',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(max_length=50, verbose_name='ハッカソン期間')),
                ('question_date', models.DateField(verbose_name='質問日')),
                ('question_content', models.TextField(verbose_name='質問内容')),
                ('answer_content', models.TextField(verbose_name='回答内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='records.course', verbose_name='コース')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='records.mentor', verbose_name='記録者')),
                ('tags', models.ManyToManyField(related_name='questions', to='records.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'db_table': 'questions',
                'ordering': ['-question_date', '-created_at'],
            },
        ),
    ]
